#!/usr/bin/env python3
import click
import subprocess
import os


def gen_index(dir):
    """
    This function calls bash script to generates file "Index" having address of
    all the songs from the given directory needed to be sync.

    arg dir: tuple of directories, from which songs need to by sync.

    Return False: if directory list is empty string.
    Return False: if shell script returns with exit status 1, that is when shell
                  script couldn't find the required directory.
    Return True: if Index is successfully generated by shell scripts.
    """

    if not dir:
        print("Expected atleast one argument.\n\nSee:\n  sync-music --help.")
        return False

    # To call shell script with given directories from subprocess.call(),
    # making this command "./generate_index.sh dir1 dir2" as a list.
    script_path=os.path.expanduser('~/.sync-music/scripts/generate_index.sh')
    call_script=list(dir)
    call_script.insert(0,script_path)
    # If call_script returns with exit status 1 for "directory not found".
    if subprocess.call(call_script):
        return False
    else:
        return True


@click.command()
@click.argument('dir', nargs=-1, required=False)
def main(dir):
    if gen_index(dir):
        print("Index generated successfully.")
    else:
        exit(1)

if __name__ == '__main__':
    main()
